language: node_js
node_js:
  - '10'
branches:
  only:
  - hexo-source
before_install:
- git config --global user.name "yeluolei"
- git config --global user.email "yeluolei@gmail.com"
- sed -i'' "s~https://github.com/yeluolei/yeluolei.github.io.git~https://${GH_TOKEN}@github.com/yeluolei/yeluolei.github.io.git~" _config.yml
install:
- yarn global add hexo-cli
- yarn install
script:
- yarn run deploy